# Generated by Django 2.2.2 on 2019-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('short_url', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('http_url', models.URLField()),
                ('visitor_count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
