# Generated by Django 2.2.2 on 2019-08-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='http_url',
            field=models.URLField(unique=True),
        ),
    ]
