# Generated by Django 2.2.2 on 2019-08-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmgmt', '0002_auto_20190801_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
